"""Tests for the DINOv2 embedding model."""

from pathlib import Path
from unittest.mock import MagicMock, patch

import numpy as np
import pytest
import torch
from PIL import Image

from xwhy.config.settings import Settings
from xwhy.models.embeddings.dinov2 import Dinov2Embedding


@pytest.fixture
def mock_settings() -> Settings:
    """Provide a mock Settings instance."""
    return Settings(embedding_cache_dir=Path("/mock/cache/dir"))


@pytest.fixture
def dinov2_embedding(mock_settings: Settings) -> Dinov2Embedding:
    """Provide a Dinov2Embedding instance initialized for CPU."""
    return Dinov2Embedding(settings=mock_settings, device="cpu")


def test_initialization(mock_settings: Settings) -> None:
    """Test proper initialization of the Dinov2Embedding class."""
    embedder = Dinov2Embedding(
        settings=mock_settings,
        model_name="custom/dinov2",
        seed=42,
        device="cpu",
    )

    assert embedder._model_name == "custom/dinov2"
    assert embedder._seed == 42
    assert embedder._device == torch.device("cpu")


@patch("xwhy.models.embeddings.dinov2.AutoModel.from_pretrained")
@patch("xwhy.models.embeddings.dinov2.AutoImageProcessor.from_pretrained")
def test_load_caching_and_seed(
    mock_processor: MagicMock,
    mock_model: MagicMock,
    dinov2_embedding: Dinov2Embedding,
) -> None:
    """Test loading the model uses the cache directory and caches instances."""
    mock_model_instance = MagicMock()
    mock_model.return_value.to.return_value = mock_model_instance

    processor, model = dinov2_embedding.load()

    expected_cache_dir = str(Path("/mock/cache/dir"))

    mock_processor.assert_called_once_with(
        "facebook/dinov2-base",
        backend="torchvision",
        cache_dir=expected_cache_dir,
    )
    mock_model.assert_called_once_with(
        "facebook/dinov2-base",
        cache_dir=expected_cache_dir,
    )

    assert processor == mock_processor.return_value
    assert model == mock_model_instance

    # Call again to ensure no redundant initialization
    dinov2_embedding.load()
    assert mock_processor.call_count == 1
    assert mock_model.call_count == 1


@patch.object(Dinov2Embedding, "load")
def test_encode_image_logic(
    mock_load: MagicMock,
    dinov2_embedding: Dinov2Embedding,
) -> None:
    """Test encode_image directly with a PIL Image, simulating mean pooling."""
    mock_processor = MagicMock()
    mock_model = MagicMock()

    def dummy_load() -> tuple[MagicMock, MagicMock]:
        dinov2_embedding._processor = mock_processor
        dinov2_embedding._model = mock_model
        return mock_processor, mock_model

    mock_load.side_effect = dummy_load

    # Mock inputs generated by processor
    mock_inputs = {"pixel_values": torch.rand(1, 3, 224, 224)}
    mock_processor.return_value.to.return_value = mock_inputs

    # Mock outputs generated by model [batch_size, seq_len, hidden_size]
    mock_outputs = MagicMock()
    mock_outputs.last_hidden_state = torch.rand(1, 257, 768)
    mock_model.return_value = mock_outputs

    dummy_image = Image.new("RGB", (224, 224))

    result = dinov2_embedding.encode_image(dummy_image)

    # Assert load was called because processor was None initially
    mock_load.assert_called_once()

    # Verify processor called with correct arguments
    mock_processor.assert_called_once_with(
        images=dummy_image,
        return_tensors="pt",
        do_rescale=False,
    )

    # Verify result shape and type
    assert isinstance(result, np.ndarray)
    assert result.shape == (768,)


@patch("xwhy.models.embeddings.dinov2.Path.is_file")
def test_encode_file_not_found(
    mock_is_file: MagicMock,
    dinov2_embedding: Dinov2Embedding,
) -> None:
    """Test standard encode method raises error for non-existent files."""
    mock_is_file.return_value = False

    with pytest.raises(FileNotFoundError, match="Image not found at path"):
        dinov2_embedding.encode("/invalid/path/image.jpg")


@patch("xwhy.models.embeddings.dinov2.Image.open")
@patch("xwhy.models.embeddings.dinov2.Path.is_file")
@patch.object(Dinov2Embedding, "encode_image")
def test_encode_delegates_to_encode_image(
    mock_encode_image: MagicMock,
    mock_is_file: MagicMock,
    mock_image_open: MagicMock,
    dinov2_embedding: Dinov2Embedding,
) -> None:
    """Test standard encode wrapper successfully delegates to encode_image."""
    mock_is_file.return_value = True

    # Mock context manager for Image.open
    mock_image_instance = MagicMock()
    mock_image_open.return_value.__enter__.return_value = mock_image_instance

    # Return a dummy numpy array from the mocked inner function
    mock_encode_image.return_value = np.array([0.1, 0.2, 0.3])

    result = dinov2_embedding.encode("/valid/path/image.jpg")

    assert isinstance(result, list)
    assert result == [0.1, 0.2, 0.3]
    mock_encode_image.assert_called_once()


@patch("xwhy.models.embeddings.dinov2.Path.is_file")
def test_encode_runtime_error(
    mock_is_file: MagicMock,
    dinov2_embedding: Dinov2Embedding,
) -> None:
    """Test encoding handles and wraps unexpected runtime errors gracefully."""
    mock_is_file.return_value = True

    # Intentionally cause an error when opening the image
    with (
        patch(
            "xwhy.models.embeddings.dinov2.Image.open",
            side_effect=OSError("Read error"),
        ),
        pytest.raises(RuntimeError, match="Failed to encode image"),
    ):
        dinov2_embedding.encode("/valid/path/image.jpg")


@patch("torch.cuda.is_available")
def test_init_device_cuda(
    mock_cuda_is_available: MagicMock, mock_settings: Settings
) -> None:
    """Test initialization defaults to 'cuda' when CUDA is available."""
    mock_cuda_is_available.return_value = True

    embedder = Dinov2Embedding(settings=mock_settings, device=None)

    assert embedder._device.type == "cuda"


@patch("torch.cuda.is_available")
def test_init_device_cpu(
    mock_cuda_is_available: MagicMock, mock_settings: Settings
) -> None:
    """Test initialization defaults to 'cpu' when CUDA is not available."""
    mock_cuda_is_available.return_value = False

    embedder = Dinov2Embedding(settings=mock_settings, device=None)

    assert embedder._device.type == "cpu"


@patch.object(Dinov2Embedding, "load")
def test_encode_image_already_loaded(
    mock_load: MagicMock,
    dinov2_embedding: Dinov2Embedding,
) -> None:
    """Test encode_image uses cached models and does not call load()."""
    mock_processor = MagicMock()
    mock_model = MagicMock()

    # Pre-populate processor and model
    dinov2_embedding._processor = mock_processor
    dinov2_embedding._model = mock_model

    # Mock inputs and outputs
    mock_inputs = {"pixel_values": torch.rand(1, 3, 224, 224)}
    mock_processor.return_value.to.return_value = mock_inputs

    mock_outputs = MagicMock()
    mock_outputs.last_hidden_state = torch.rand(1, 257, 768)
    mock_model.return_value = mock_outputs

    dummy_image = Image.new("RGB", (224, 224))

    result = dinov2_embedding.encode_image(dummy_image)

    # Ensure load was NOT called because they were already loaded
    mock_load.assert_not_called()
    mock_processor.assert_called_once()
    assert isinstance(result, np.ndarray)


@patch("torch.cuda.is_available")
@patch("torch.cuda.manual_seed_all")
def test_set_seed_with_cuda(
    mock_manual_seed_all: MagicMock,
    mock_cuda_is_available: MagicMock,
    dinov2_embedding: Dinov2Embedding,
) -> None:
    """Test _set_seed configures cudnn and cuda seeds if CUDA is available."""
    mock_cuda_is_available.return_value = True

    dinov2_embedding._set_seed()

    # Use assert_called_with instead of assert_called_once_with
    # because torch.manual_seed also calls torch.cuda.manual_seed_all internally
    mock_manual_seed_all.assert_called_with(dinov2_embedding._seed)

    assert torch.backends.cudnn.deterministic is True
    assert torch.backends.cudnn.benchmark is False


def test_get_cache_dir_fallback() -> None:
    """Test _get_cache_dir falls back to ~/.cache/xwhy/embeddings if not set."""
    # Use MagicMock to bypass Pydantic's strict type validation
    mock_settings = MagicMock()
    mock_settings.embedding_cache_dir = None

    # Initialize the embedder with the mocked settings
    embedder = Dinov2Embedding(settings=mock_settings, device="cpu")

    expected_path = Path.home() / ".cache" / "xwhy" / "embeddings"
    assert embedder._get_cache_dir() == expected_path


def test_dinov2_model_property_unloaded(dinov2_embedding: Dinov2Embedding) -> None:
    """Test model property raises RuntimeError when not loaded."""
    dinov2_embedding._model = None
    dinov2_embedding._model_name = "dinov2"
    with pytest.raises(RuntimeError, match="not loaded"):
        _ = dinov2_embedding.model


def test_dinov2_processor_property_unloaded(dinov2_embedding: Dinov2Embedding) -> None:
    """Test processor property raises RuntimeError when unloaded."""
    dinov2_embedding._processor = None
    dinov2_embedding._model_name = "dinov2"
    with pytest.raises(RuntimeError, match="not loaded"):
        _ = dinov2_embedding.processor


def test_dinov2_call_loads_if_none(dinov2_embedding: Dinov2Embedding) -> None:
    """Test __call__ loads model and processor if they are None."""
    dinov2_embedding._processor = None
    dinov2_embedding._model = None

    mock_processor = MagicMock()
    mock_model = MagicMock()
    mock_mean = MagicMock()
    mock_mean.squeeze().cpu().numpy.return_value = np.array([4.0])
    mock_model.return_value.last_hidden_state.mean.return_value = mock_mean

    dinov2_embedding.load = MagicMock(return_value=(mock_processor, mock_model))  # type: ignore[method-assign]

    mock_input = MagicMock(spec=torch.Tensor)

    dinov2_embedding(inputs=mock_input)

    dinov2_embedding.load.assert_called_once()


def test_dinov2_call_with_image(dinov2_embedding: Dinov2Embedding) -> None:
    """Test __call__ correctly processes a PIL Image input."""
    mock_processor = MagicMock()
    mock_processor.return_value.to.return_value = {"pixel_values": "tensors"}
    dinov2_embedding._processor = mock_processor

    mock_model = MagicMock()
    mock_mean = MagicMock()
    mock_mean.squeeze().cpu().numpy.return_value = np.array([1.0])
    mock_model.return_value.last_hidden_state.mean.return_value = mock_mean
    dinov2_embedding._model = mock_model

    image = MagicMock(spec=Image.Image)
    result = dinov2_embedding(inputs=image)

    mock_processor.assert_called_once()
    assert isinstance(result, np.ndarray)


def test_dinov2_call_with_dict(dinov2_embedding: Dinov2Embedding) -> None:
    """Test __call__ correctly processes a dictionary of tensors."""
    dinov2_embedding._processor = MagicMock()
    mock_model = MagicMock()
    mock_mean = MagicMock()
    mock_mean.squeeze().cpu().numpy.return_value = np.array([2.0])
    mock_model.return_value.last_hidden_state.mean.return_value = mock_mean
    dinov2_embedding._model = mock_model

    mock_tensor = MagicMock()
    mock_tensor.to.return_value = "moved_tensor"

    _ = dinov2_embedding(inputs={"pixel_values": mock_tensor})

    mock_tensor.to.assert_called_once_with(dinov2_embedding._device)
    mock_model.assert_called_once_with(pixel_values="moved_tensor")


def test_dinov2_call_with_tensor(dinov2_embedding: Dinov2Embedding) -> None:
    """Test __call__ correctly processes a single tensor input."""
    dinov2_embedding._processor = MagicMock()
    mock_model = MagicMock()
    mock_mean = MagicMock()
    mock_mean.squeeze().cpu().numpy.return_value = np.array([3.0])
    mock_model.return_value.last_hidden_state.mean.return_value = mock_mean
    dinov2_embedding._model = mock_model

    mock_tensor = MagicMock(spec=torch.Tensor)
    mock_tensor.to.return_value = "moved_tensor"

    dinov2_embedding(inputs=mock_tensor)

    mock_tensor.to.assert_called_once_with(dinov2_embedding._device)
    mock_model.assert_called_once_with("moved_tensor")


def test_dinov2_model_property_loaded(dinov2_embedding: Dinov2Embedding) -> None:
    """Test model property returns the model when it is successfully loaded."""
    dinov2_embedding._model = "dummy_loaded_model"

    # It should not raise an error and should return the exact assigned value
    assert dinov2_embedding.model == "dummy_loaded_model"


def test_dinov2_processor_property_loaded(
    dinov2_embedding: Dinov2Embedding,
) -> None:
    """Test processor property returns the processor when it is successfully loaded."""
    dinov2_embedding._processor = "dummy_loaded_processor"

    # It should not raise an error and should return the exact assigned value
    assert dinov2_embedding.processor == "dummy_loaded_processor"
