"""Visualization plotting functions for XWhy results."""

from xwhy.plots.base import BaseTextPlotter
from xwhy.plots.factory import TextPlotterFactory
from xwhy.plots.image import (
    get_image_and_mask,
    image_boundaries,
    image_heatmap,
    image_regions,
    image_regions_side_by_side,
    plot_image,
)
from xwhy.plots.plots import (
    bar,
    beeswarm,
    decision,
    embedding,
    force,
    group_difference,
    heatmap,
    image,
    image_to_text,
    initjs,
    monitoring,
    partial_dependence,
    plot_feature_bar_chart,
    plot_feature_box_plot,
    scatter,
    text,
    text_heatmap,
    violin,
    waterfall,
)
from xwhy.plots.point_cloud import (
    create_clean_3d_layout,
    create_point_cloud_trace,
    create_rotation_frames,
    display_plotly_figure,
    plot_3d_mesh,
    plot_3d_point_cloud,
    plot_colored_3d_point_cloud,
    plot_point_cloud,
    plot_point_cloud_clusters,
)
from xwhy.plots.tabular import (
    plot_dataset,
    plot_explanation_waterfall,
    plot_feature_contributions,
    plot_method_contributions,
)
from xwhy.plots.text import NativeHeatmapPlotter
from xwhy.plots.types import TextPlotterType
from xwhy.plots.visualisation import Explanation

__all__ = [
    "BaseTextPlotter",
    "Explanation",
    "NativeHeatmapPlotter",
    "TextPlotterFactory",
    "TextPlotterType",
    "bar",
    "beeswarm",
    "create_clean_3d_layout",
    "create_point_cloud_trace",
    "create_rotation_frames",
    "decision",
    "display_plotly_figure",
    "embedding",
    "force",
    "get_image_and_mask",
    "group_difference",
    "heatmap",
    "image",
    "image_boundaries",
    "image_heatmap",
    "image_regions",
    "image_regions_side_by_side",
    "image_to_text",
    "initjs",
    "monitoring",
    "partial_dependence",
    "plot_3d_mesh",
    "plot_3d_point_cloud",
    "plot_colored_3d_point_cloud",
    "plot_dataset",
    "plot_explanation_waterfall",
    "plot_feature_bar_chart",
    "plot_feature_box_plot",
    "plot_feature_contributions",
    "plot_image",
    "plot_method_contributions",
    "plot_point_cloud",
    "plot_point_cloud_clusters",
    "scatter",
    "text",
    "text_heatmap",
    "violin",
    "waterfall",
]
